/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.GUI;

import UI.IView;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Eugen
 */
public class GuiView extends javax.swing.JFrame implements IView {

    
    /**
     * Creates new form GuiView
     */
    public GuiView() {
        super("Start");
        initComponents();
        
        Toolkit tk = this.getToolkit();
        Dimension dim = tk.getScreenSize();
        setLocation((int)(dim.getWidth() - getWidth())/2, (int)(dim.getHeight() - getHeight())/2);       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelStart = new javax.swing.JPanel();
        jlblHospitalName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jbtnAdministration = new javax.swing.JButton();
        jbtnDoctor = new javax.swing.JButton();
        jbtnNurses = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanelStart.setBackground(new java.awt.Color(255, 255, 255));

        jlblHospitalName.setFont(new java.awt.Font("Baskerville Old Face", 1, 48)); // NOI18N
        jlblHospitalName.setText(" Virgo Hospital");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/hospital.png"))); // NOI18N

        jbtnAdministration.setBackground(new java.awt.Color(204, 204, 255));
        jbtnAdministration.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtnAdministration.setText("ADMINISTRATION");
        jbtnAdministration.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jbtnAdministration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAdministrationActionPerformed(evt);
            }
        });

        jbtnDoctor.setBackground(new java.awt.Color(204, 204, 255));
        jbtnDoctor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtnDoctor.setText("DOCTORS");
        jbtnDoctor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jbtnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDoctorActionPerformed(evt);
            }
        });

        jbtnNurses.setBackground(new java.awt.Color(204, 204, 255));
        jbtnNurses.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtnNurses.setText("NURSES");
        jbtnNurses.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        jbtnNurses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNursesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelStartLayout = new javax.swing.GroupLayout(jPanelStart);
        jPanelStart.setLayout(jPanelStartLayout);
        jPanelStartLayout.setHorizontalGroup(
            jPanelStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelStartLayout.createSequentialGroup()
                .addGroup(jPanelStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStartLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jlblHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelStartLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(jPanelStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnNurses, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnAdministration, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(124, 124, 124))
        );
        jPanelStartLayout.setVerticalGroup(
            jPanelStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStartLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanelStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelStartLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jbtnNurses, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jbtnDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelStartLayout.createSequentialGroup()
                        .addGroup(jPanelStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnAdministration, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelStart, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAdministrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAdministrationActionPerformed
        Administration administration = new Administration();
        this.dispose();
        administration.setVisible(true);
    }//GEN-LAST:event_jbtnAdministrationActionPerformed

    private void jbtnNursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNursesActionPerformed
        Nurses nurses = new Nurses();
        this.dispose();
        nurses.setVisible(true);
    }//GEN-LAST:event_jbtnNursesActionPerformed

    private void jbtnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDoctorActionPerformed
        Doctors doctors = new Doctors();
        this.dispose();
        doctors.setVisible(true);
    }//GEN-LAST:event_jbtnDoctorActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        
    }

    @Override
    public void Start() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelStart;
    private javax.swing.JButton jbtnAdministration;
    private javax.swing.JButton jbtnDoctor;
    private javax.swing.JButton jbtnNurses;
    private javax.swing.JLabel jlblHospitalName;
    // End of variables declaration//GEN-END:variables
}
